### PR TITLE
Add a test for ProcessController::request (the request form)

### PR DESCRIPTION
**Pull request by froulet**
This commit adds a test for the ProcessController:request method (the request form)
(issue https://github.com/tgalopin/enpremiereligne.fr/issues/4)

### CODE REVIEW

**Comment by tgalopin** [comment]
This is awesome @froulet, thanks very much! 

I just realized that actions are not ran on PR due to a missing configuration in my YAML file. I fixed the problem in master, could you rebase on it so that you can run the CI :) ?

Thanks!

**Comment by froulet** [comment]
You're very welcome!
My pleasure to help you out.

A suggestion:
Maybe the coding style requirements (and the commands needed to run it) could be included in the incoming CONTRIBUTING.md file https://github.com/tgalopin/enpremiereligne.fr/pull/14?
Otherwise, maybe the linter could be run automatically in the CI?

**Comment by tgalopin** [comment]
It does run doesn't it? https://github.com/tgalopin/enpremiereligne.fr/pull/26/checks?check_run_id=519480247

**Comment by tgalopin** [comment]
Merci !

**Comment by froulet** [comment]
> It does run doesn't it? https://github.com/tgalopin/enpremiereligne.fr/pull/26/checks?check_run_id=519480247

It does indeed, very well moreover :D !
I was thiking about auto-linting the files.
Otherwise, just adding the command 'php-cs-fixer fix --config .php_cs.dist tests/ src/' in the incoming CONTRIBUTING.md could help people spot their code styling issues.

**Comment by froulet** [comment]
Avec plaisir :D ! N'hésite à me donner les priorités si il reste des points urgents.

**Pull request merged**
